# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactiveCocoaDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactiveCocoaDemo
use_frameworks!
pod 'ReactiveCocoa', '~> 4.0.2-alpha-1'

end
